site_name: LMC Minecraft Server
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: lime

nav:
  - Home: index.md
  - Rules: rules.md
  - Players: players.md
  - BlueMap: bluemap.md
  - Claims: claims.md
  - Worlds: worlds.md
  - Parkour: parkour.md
  - Join: join.md
  - Builds: builds.md
